---
all:
  children:
    cisco_devices:
      hosts:
        Core_Switch:
          ansible_host: 10.100.2.2
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_network_os: ios
          ansible_connection: network_cli
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        IDF3_Camera:
          ansible_host: 10.100.202.233
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        IDF1:
          ansible_host: 10.100.202.241
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        IDF7:
          ansible_host: 10.100.202.247
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        IDF2:
          ansible_host: 10.100.202.242
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        IDF5_Camera:
          ansible_host: 10.100.202.235
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        IDF3A:
          ansible_host: 10.100.202.248
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        IDF5:
          ansible_host: 10.100.202.245
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        IDF6_Camera:
          ansible_host: 10.100.202.236
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        IDF6:
          ansible_host: 10.100.202.244
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        IDF4:
          ansible_host: 10.100.202.246
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        IDF4_Camera:
          ansible_host: 10.100.202.234
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        IDF1_Camera:
          ansible_host: 10.100.202.231
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        IDF2_Camera:
          ansible_host: 10.100.202.232
          ansible_user: rugs_admin
          ansible_password: 3.Wise.Monkeys
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        Fortinet:
          ansible_host: 10.17.10.1
          ansible_user: admin
          ansible_password: RUGS@dm1n!
          ansible_connection: network_cli
          ansible_network_os: fortios
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
        Meraki_AP:
          ansible_host: 10.100.2.1
          ansible_user: admin
          ansible_password: merakipass
          ansible_connection: httpapi
          ansible_network_os: meraki
          ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'