---
- name: Show version on Cisco devices
  hosts: cisco_devices
  gather_facts: no
  
  tasks:
    - name: Run show version command
      cisco.ios.ios_command:
        commands:
          - show version
      register: version_output
    
    - name: Display version output
      debug:
        var: version_output.stdout_lines
