- name: Show version on Cisco devices
  hosts: all
  gather_facts: no
  tasks:
    - name: Run 'show version'
      cisco.ios.ios_command:
        commands:
          - show version
      register: version_output

    - name: Extract version line
      set_fact:
        ios_version_line: "{{ version_output.stdout[0].split('\n') | select('search', '^Cisco IOS Software') | list | first }}"

    - name: Display just the version line
      debug:
        msg: "Switch is running: {{ ios_version_line }}"